### ISSUE TITLE
【需求】可以增加每个设备每日上传/下载流量统计吗？

### ISSUE THREAD

**Issue by Asakushen** [bcrjl/miwifi-agent#1]
有统计每个设备每日的上传下载需求，希望可以增加。
另外设备列表里的下载速度和上传速度似乎也是最大值？最大值几乎不太具备统计学意义，考虑能否改为平均值？
感谢您的开发。

**Comment by qingshanking** [comment]
1.做统计的话，服务就需要增加数据库了，而且还需要定时取路由器数据，感觉路由器扛不住啊，目前是只有使用的时候去调实时接口，数据没有存储。
2.单个设备的数据上传和下载的话，这调路由器的数据太频繁了，还是一句话，路由器扛不住。

其实说白了，首页的统计数据，只是一个参考，如果具体到详情和设备，路由器扛不住，八成会影响路由器性能。

**Comment by Asakushen** [comment]
好的了解了，感谢解答。

**Comment by qingshanking** [comment]
要是路由器性能够强悍，怎么折腾都可以。关键这玩意，家用的，我出这个服务，主要作用是想集成一些它的部分服务，如端口映射、DDNS这些东西，然后集成到第三方平台里面。

**后期如果不考虑性能的话，我可以试着把你这个需求实现。**

**Comment by Asakushen** [comment]
hhh，确实。主要我看米家app内有每个设备的流量使用情况，所以想到了能否放在这个项目里。网页总是比app简单直接的。至于平均速度这个倒是不重要。我感觉每日每个设备的流量统计官方应该是有接口的吧，不然米家app路由器管理这里是如何实现的呢。

**Comment by qingshanking** [comment]
app上没看到有每日统计量啊

**Comment by qingshanking** [comment]
这个就是我设备列表的数据

![5ec57636e0908e13940fe4cbbae20c9](https://github.com/bcrjl/miwifi-agent/assets/22401257/13046eb3-5883-4637-88b1-dc167438672d)

**Comment by Asakushen** [comment]
啊，是我表述不够清楚，app内有流量消耗统计，我想的是可以每日23：59获取一下 就当作今天的流量统计。
但他这个似乎是这个设备连接以来的流量消耗，不确定会不会隔日刷新。也就是说设备断开再连接后肯定会重置，这似乎会是个问题

**Comment by qingshanking** [comment]
路由器重启后，这个数据就会清掉的。方便加个联系方式沟通一下吗

**Comment by qingshanking** [comment]
我在项目的README.md增加一个qq群链接

**Comment by Asakushen** [comment]
好的 老哥 已申请
